---
title: "A Systematic Review of the Use of the ESM Methodology in Education"
author: "Alex Lishinski, Michael Mann, Omiya Sultana"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Introduction

This study is a systematic review of studies that used the experience sampling method to collect data in education settings.
Another new line
What else 
Okay
New line to test 

The experience sampling method (ESM) is a longitudinal data collection method that involves gathering data frequently from participants over an extended period of time. The use of ESM in education research is on the rise in recent years because it provides a unique way to collect data closer in time to students’ experiences that are of interest to researchers, and so this method provides a unique measure of ecological validity

Whereas some studies in education might involve, for example, collecting data from students 3-4 times over the course of a semester, an ESM study might involve collecting data from students 6 times a day for a week. 

This is but one example of course, as there are infinitely many variations of ways that one could conduct an ESM study. The purpose of this systematic review is to review and code all of the studies in education that have used ESM, in order to aggregate data about their methodological choices and capture the typical ways that this methodology is used in education research.

Technology is used in various ways to conduct ESM studies. ESM relies on collecting data in the moment, and this often involves prompting participants to complete survey instruments at important times. These signals are done using many different kinds of devices, such as watches, beepers, smartphones running specialized ESM apps, etc. Surveying in ESM can also be done without an explicit signal from a signalling device. Many ESM studies use event contingent sampling, where participants are instructed to complete surveys at defined junctures in the day, such as at the end of a class period.

## Advantages of ESM in Education

# Literature Review

ESM was developed by Larson and Csikszentmihalyi (1983). ESM studies are also sometimes called “daily diary method” or “ecological momentary assessment” (EMA).

The book Experience Sampling Method by Hektner, Schmitdt and Csikszentmihalyi (2007) provides an overview of ESM variations.     

# The Present Study

The purpose of this systematic review is to provide a comprehensive cataloging of the ways that the ESM method has been used in education research studies.

# Method


The literature search for this study was conducted over 2 databases, EBSCO and SCOPUS. We searched for all articles including the terms “ESM”, “Experience Sampling” “Experience Sampling Method”, “Experience Sampling Approach”, “Experience Sampling Study”, and “Experience Sampling Studies”. To find the articles, we used 2 different search queries for the two databases. 

In the EBSCO database we used the search query “"experience sampling" N3 (method* OR approach* OR study OR studies)” and initially found 345 results. Then we reviewed the title, keywords, and abstract for each article carefully to determine whether they are studies in the domain of education and whether they indeed used ESM as their data collection method. This initial screening resulted in 128 articles that looked relevant to this study. 

Then we searched the SCOPUS database using the query "Experience Sampling Method"  AND  (education  OR  learning  OR  instruction  OR  teach*  OR  student* ). This search resulted in 197 articles. We then screened these articles the same way as the EBSCO articles to determine whether they were in the domain of education and that they used ESM as their data collection method. This screening resulted in 77 articles that looked relevant to this study. 

Between EBSCO and SCOPUS we ended up with 205 articles from the two searches. However, there were some duplicates between the two databases, and after deleting the duplicates, we had 162 articles for this study. We also included 18 articles from another search that was done prior to EBSCO and Scopus database search. As a result, we have 180 articles in total to code for this study. However, through the coding process, we found that some of the articles that passed the initial screening were not in the scope of this study. For example, Ito (2016) paper’s target group is students and they used ESM, but they explore students’ leisure experience using ESM. That’s why we did not include this article in our study. Moreover, we found examples where multiple articles used the same dataset. In those cases, we coded the article that was published first (example???). Finally, after coding the articles and eliminating some that were out of scope, we ended up with XXX articles that are in our study scope. 

Table: Elements of the Systematic Review for Publications About ESM

|Element           |Steps Taken                                            |
|------------------|-------------------------------------------------------|
|Sampling strategy |Comprehensive search for all journal articles about ESM|
|Type of study     |Search of the EBSCO database and SCOPUS database       |
|Approaches	       |Search of the EBSCO database and SCOPUS database       |
|Range of years    |1989 to 2020                                           |
|Limits            |Published in the english language                      |
|Inclusion criteria|“ESM”, “Experience Sampling” “Experience Sampling Method”, “Experience Sampling Approach”, “Experience Sampling Study”, or “Experience Sampling Studies” are included in the title, keyword or abstract           |
|Terms used        |“ESM”, “Experience Sampling” “Experience Sampling Method”, “Experience Sampling Approach”, “Experience Sampling Study”, and “Experience Sampling Studies”                                                          |
|Electronic sources|The citation reference software Endnote                |


A coding frame was developed to code the articles for the different methodological details of the study. The categories coded for included construct(s) studied, content area, age/level of target population, sample size, prompting method, number of signals, length of signaling period, response rate, signalling method, items used, number of items, validity and reliability information provided, missing data strategy, and type of analysis used.

Articles were coded by 3 researchers for each of the above categories. The coding frame was developed prior to the preliminary rounds of coding. Several preliminary rounds of coding were conducted to refine the coding frame and practice the coding procedure, and these codes were not included in the final data for analysis.

## Sample 

## Coding

## Discription of areas of interest (coding)
 **will work on further description and detail**
 
### Construct
We wanted to find out the extent that the research literature has covered as themes of their studies. We have seen that constructs have a variability of depth, some coding for the construct was the singular focus. While other articles investigated several constructs and are broad in the scope that they cover. During interrater sessions, when there was more than one construct studied, we discussed which one is the primary focus and what constructs were supplementary to the main. Some articles did have more than one main construct. 
The most studied constructs included but limited to:
Student engagement, motivations, emotion, affect (including focus on______________), flow, etc. ESM has been used in studying main different constructs. 

### Content Area
Article in this review especially when looking at the elementary, middle, or secondary level were investigated where there was not one content area. The cross-content focused on the individual not which domain/course/class they were participating in. 
Determining what domains of knowledge (content areas) researchers have used the ESM to investigate helps us to understand the breadth of content areas that researchers have used ESM to research. Investigating the extent of content areas researchers within ESM will allow future researchers to expand the current domains or extend the usage of ESM into more content areas. Also, ESM has been used to investigate math, science, band, psychology, and other content areas. 

### Age/Grade Level
ESM has been used across many grade levels and ages. Students from elementary grades, starting at grade ___ and through the middle, secondary, post-secondary, and in professional settings. 

### Role of the participant
The main focus of participants were students, but others included teachers or industry workers. The role of each participant differed according to the focus of the researcher.  Due to the extensive usage that ESM can be enacted in researching psychometrics the roles of the participants varies along with the variability of content areas and age of participants. Most of the participants are students, but not limited to that demographic. 


### Sample Size
The sample size was investigated to determine how many participants were in each of the studies. The sample size ranged from 1 participant to a study with over one thousand student participants. Determining and coding for sample size was difficult depending on the article. Some studies would refer to their sample size as the number of participants, yet they ran their analysis with less than the originally stated value. During inter-rator training, we determined that the sample size would be the number of individuals that were analyzed and contributed to the data. 

### Prompting Method
For a study to be truly and ESM study, the participants needed to receive some form of prompt that would signal the participant to contribute. The prompting method refers to when and what style that participants were signaled. For example, in some studies participants were signaled at random times during a given period, this could either be during a class period, a lab, or even random times during an entire day. Other studies used set time as their prompting method. Participants would be signaled at specific times during the day. Then others would use the participants' schedule as the frame for a set time that they would answer survey questions, such as their bedtime or during study time for their courses. 

### Number of Signals
Signals affect the power of the study. It is said the more signals the better, this depends on what you are investigating and how long you have to run the study. During coding determining the number of signals each of the participants received was not stated overtly. On occasion, we would have to take bits of information that were provided by the authors and mathematically estimate the number of signals that the participants received. Some of the information that was provided was the number of signals that were sent in total and then we would have to divide that by the number of participants. This gave us a decent estimate of the number of signals sent. This became difficult when articles that stated the number of participants were different throughout the paper. 
Others would not even provide how many times each participant received signals to participate in the ESM study. We, the coders, could not extrapolate the number of signals from the information that was provided to us. Then finally, there were some articles where the authors provided exact numbers of how many signals each person received. 
We had difficulty when authors would state the number of signals per day, but did not provide a definite number of days, weeks, or months for the ESM study. These papers had such limited facts of length that we could not calculate the number of signals that participants received. 

### Length of Signaling Period (study length)
This is a determining factor for determining how many signals a participant received. The longer the signaling period tended to equate to more signals received by the individual participants. The signal length varied widely, from 1 lesson on a single day to 7 weeks or another that was vague and stated it occurred over a whole semester. 
Coding for the signaling period was difficult at times. Some of the authors overtly stated the length of the period, while others did not give any indication of how long the ESM was used. This also caused a problem when determining the number of signals that students received. 

### Response Rate
During the coding of the review papers, this became something that we would continually look for in a paper. Many papers (n=  ) did not provide the reader with the response rate for their study. This takes away from the power of the study. There were other times we were required to calculate the response rate. We would use the number received and divide by the number of participants. This was difficult at times when the number of participants was unclear. 

### Signal Method
How were participants informed when it was time for them to fill out the survey/questionnaires.
ESM has evolved in the methods that the participants are signaled when to fill out the surveys, questionnaires, or other documents. Signaling methods were sometimes not provided, but other factors in the paper such as the authors stating that it was an ESM study allowed us the justification to keep the study in this review. 
Signaling methods were as simple as a pencil or pen and a piece of paper done in the classroom setting signaled by the teacher. Other we combined in a packet that was taken home and combined with a pager or other electronic device. 
Devices that ESM researchers used included: pager, cell phone (later transformed to “app”), also apps that could be used on tablets (Android, iPad, etc.), PDA, and text messages. Some of the originals coded for signaling methods were transformed and evolved as we discussed coding and came to a consensus. For example, we looked at the usage of cell phones as one single code, but later we separated into apps for those that were not a form of text messages and text messages. Then text messages were further described, coded, as SMS since the ESM programs usually use an SMS format for sending messages to participants. 

### Items used
We also focused on the designs of the investigation, what type of question models researchers used. For example, each of the items that researchers used was instruments to determine what each participant was experiencing. Researchers many times used a type of Likert scale, psychometric scale, which varied from a 3 point Likert scale up to a 100-point Likert scale. This varied according to the needs and the objectives of the researchers.  Then researchers would use open-ended questions to enable participants to elaborate on their experiences. Finally, some authors were unclear of what instruments were used. They would only state that they used a questionnaire and no further information was provided. 

### Description of items
To further draw information and specifics of the ESM that was used in research we looked at what types of topics the items were seeking to glean data from the participants. We wanted to know what kinds of question topics that have been used in the current literature. Some articles would only elaborate and say that more than one Likert scale was used, while others would go into detail about the different topics. For example, in the Shumow et al. (2008), they had 3 items on the cognitive state, 4 on affective, 2 on the motivational state, and 2 indication student self-views.  Detail of what items were used it students varied from detailed to no information provided, minus what kind of items, instruments, were used in their study. 

### Number of Items
We wanted to know the number of items that were used in each of the articles. Some would only use a single item to determine the experience of the participants, while others would use up to 86 items in their surveys. 

### Validity and Reliability
For Validity and Reliability, we focused on the authors providing a Cronbach’s alpha or not. Though there are other methods to determine validity and reliability, an alpha value is commonly used and effective when determining the significance of using a Likert scale questionnaire. At the beginning of coding, we discussed other methods for Validity and Reliability, such as P-value and others, but we came to a consensus that alpha would be the most functional and over encompassing for this review with the number of articles that used Likert scales as their instruments.

### Missing Data Strategies
Researchers accounting for why certain collected data were not analyzed. 
Though many articles did not provide the reader an accounting for removal or lack of data. Some articles did give and account for missing data by using, for example, Full Information Maximum Likelihood (FIML), listwise deletion, or pairwise elimination.




### Types of Analysis 

How did the researcher analyze the data? Authors used different terms for similar analysis.


## Strategies for Validating Findings and Establishing Reliability

Interrater reliability 
 
# Results

Each of the categories was coded for each of the studies listed, and the aggregates of these codes are shown below. 


## Aggregation of results

Here we will include summary tables for the codes that can be summarized in this format:

* content area
* Age / grade level
* Role of participant
* sample size
* prompting method
* number of signals
* length of signaling period 
* signaling method
* Type of analysis used

Then there are categories that will require additional contextualization

* response rate 
* missing data strategy


### Construct studied 

Then we will talk about the construct studied code

1 paragraph describing the process of coding this and the challenges of different terminology

1 paragraph breaking down the results as we categorized them

Then paragraphs on the most commonly occurring constructs

* Emotions
* Engagement
* Flow
* Self-efficacy

These paragraphs should:
* Describe the construct in more detail and variations 
* Describe the types of items that were used to measure it
* Give examples of some of the findings from the articles measuring this construct
* Summarize if possible


# Discussion

The purpose of this systematic review was to document the methodological variation in ESM studies in education. 

Overall we found some categories where there was significant commonalities across studies, e.g. XX% of studies were studying the constructs of X, Y, and Z. Almost all of the studies were with undergraduate students. XX% of studies used HLM models to analyze data of responses nested in persons.

There were some categories where there was significant variation.

Other categories revealed some interesting insights that defy easy categorization.



 

